name: worm-preprocess
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - ipykernel
  - pytorch
  - numpy
  - pandas
  - scipy
  - h5py
  - mat73
  - scikit-learn
  - xlrd>=2.0.1
  - openpyxl
  - pyarrow # for parquet file creation
  - matplotlib # for connectome graph visualization
  - pip
  - pip:
      - torch-geometric
      - tqdm
      - pynwb
# Use conda env update --file environment.yml --prune to update environment 
# after changing dependencies